version: 2

models:
  - name: dim_products
    description: Cleansed table which contains list of product from Mexico Toys
    columns: 
      - name: product_id
        description: Primary key for the product
        data_tests:
          - unique
          - not_null
      - name: product_name
        description: Name of the product
        data_tests:
          - not_null
      - name: product_category
        description: Category of the product
        data_tests:
          - not_null
      - name: product_cost
        description: Cost of the product
      - name: product_price
        description: Price of the product

  - name: dim_stores
    description: Cleansed table which contains information all stores of Mexico Toys
    columns:
      - name: store_id
        description: Name of the store
        data_tests:
          - not_null
          - unique
      - name: store_name
        description: Name of the store
        data_tests:
          - not_null
      - name: store_city
        description: City of the store
        data_tests:
          - not_null
      - name: store_location
        description: Location of the store
        data_tests:
          - not_null
      - name: store_open_date
        description: Date of the store open
        data_tests:
          - not_null
  
  - name: fact_inventory
    description: Cleansed table inventory to store all information regarding product stock
    columns:
      - name: store_id
        description: Id of the store
        data_tests: 
          - not_null
          - relationships:
              to: ref('dim_stores')
              field: store_id
      - name: product_id
        description: Id of the product
        data_tests: 
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
  - name: fact_sales
    description: Cleansed table sales to store all the sale transactions
    columns:
      - name: sale_id
        description: Id of the sales
        data_tests: 
          - not_null
          - unique
      - name: sale_date
        description: date of the sales made
        data_tests:
          - not_null
      - name: store_id
        description: Id of the store
        data_tests: 
          - not_null
          - relationships:
              to: ref('dim_stores')
              field: store_id
      - name: product_id
        description: Id of the product
        data_tests: 
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
